server/sonar-web/src/main/js/apps/organizationMembers/ManageMemberGroupsForm.tsx
CD-1937 "api/users/groups" API call parameters fixed.
=> CD-1936-getUserGroups-API-call-fix

server/sonar-web/src/main/js/apps/groups/components/App.tsx
Organization support added to groups component.
=> CD-1947 Groups tab cannot be accessed by anyone

server/sonar-web/src/main/js/apps/groups/components/App.tsx, server/sonar-web/src/main/js/apps/groups/components/EditMembers.tsx, server/sonar-web/src/main/js/apps/groups/components/EditMembersModal.tsx, server/sonar-web/src/main/js/apps/groups/components/List.tsx, server/sonar-web/src/main/js/apps/groups/components/ListItem.tsx
Successfully tested in local instance.
=> CD-1949 organization parameter added for "api/user_groups/users" API

server/sonar-web/src/main/js/apps/groups/components/EditMembersModal.tsx, sonar-core/src/main/resources/org/sonar/l10n/core.properties
Update user pop-up screen after the changes.
=> CD-1957 Adding Group name to Update users pop-up screen.

server/sonar-ce-task-projectanalysis/src/main/java/org/sonar/ce/task/projectanalysis/component/BranchPersisterImpl.java, server/sonar-ce-task-projectanalysis/src/test/java/org/sonar/ce/task/projectanalysis/component/BranchPersisterImplTest.java
=> CD-1951 exclude branches without target-branch from branch-purge

sonar-core/src/main/java/org/sonar/core/config/PurgeProperties.java, sonar-core/src/test/java/org/sonar/core/config/CorePropertyDefinitionsTest.java, sonar-core/src/test/java/org/sonar/core/config/PurgePropertiesTest.java
=> CD-1951 Add daysBeforeDeletingInactiveBranchesAndPRs prop

server/sonar-web/src/main/js/api/codescan.ts, server/sonar-web/src/main/js/apps/organizations/actions.ts, server/sonar-web/src/main/js/apps/projectDeletion/Form.tsx, server/sonar-web/src/main/js/apps/projectDeletion/__tests__/Form-test.tsx, server/sonar-web/src/main/js/apps/projectsManagement/DeleteModal.tsx, server/sonar-web/src/main/js/apps/projectsManagement/__tests__/DeleteModal-test.tsx
Calling codescan APIs for: 
1. Organization Deletion
2. Project Deletion
3. Bulk Project Deletion
=> CD-1969 API change for Project, Org and Bulk-Projects deletion

server/sonar-ce-task-projectanalysis/src/main/java/io/codescan/sonarqube/codescanhosted/ce/CodeScanBranch.java, server/sonar-ce-task-projectanalysis/src/main/java/io/codescan/sonarqube/codescanhosted/ce/CodeScanBranchLoaderDelegate.java, sonar-scanner-engine/src/main/java/io/codescan/sonarqube/codescanhosted/scanner/CodeScanBranchConfigurationLoader.java
=> CD-1992: Pull Requests support

sonar-plugin-api/src/main/java/org/sonar/api/issue/Issue.java
Increase MESSAGE_MAX_SIZE  to allow detailed Issue Messages.
=> CD-1913 Update MAX_MESSAGE_SIZE

server/sonar-db-dao/src/main/java/org/sonar/db/rule/RuleForIndexingDto.java, server/sonar-db-dao/src/main/resources/org/sonar/db/rule/RuleMapper.xml, server/sonar-server-common/src/main/java/org/sonar/server/rule/index/RuleDoc.java, server/sonar-server-common/src/main/java/org/sonar/server/rule/index/RuleIndex.java, server/sonar-server-common/src/main/java/org/sonar/server/rule/index/RuleIndexDefinition.java
=> CD-2075: Use organization_uuid as ES filter in Rules search

build.gradle, sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RuleParamType.java
Add new RuleParamType  "KEY_VALUE_MAP" added to support UI feature of enabling user to specify rule parameters in key-value format. 
Example: CD-1906 and CD-1907 are rules which use this rule parameter.
=> CD-2180 Add KEY_VALUE_MAP to RuleParamType

sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RuleParamType.java
Add commits related to Release 22.1 to codescan-hotfix-22.1 branch
=> Move changes from codescan-impl-8.5 to codescan-hotfix-22.1

server/sonar-web/src/main/js/apps/organizations/components/OrganizationEdit.tsx
There was an existing react component present '**OrganizationUrlInput**' which is being used in Manual Org creation page for validating Org URL.
Used the same component in update org page to accept Org URL.
=> CD-2256 Org URL validation added to prevent XSS security issue

server/sonar-web/src/main/js/app/components/nav/global/GlobalNavMenu.tsx, server/sonar-web/src/main/js/app/styles/init/misc.css, server/sonar-web/src/main/js/apps/create/components/OrganizationKeyInput.tsx
Pull Request contains fix for 
1. **CD-2226** - Create new organization screen has the following issues:
2. **CD-2228** -  MyIssues tab should show issue assigned to currently logged-in user.
=> Cd-2226/2228 Fix

server/sonar-web/src/main/js/api/codescan.ts, server/sonar-web/src/main/js/app/components/ComponentContainer.tsx, server/sonar-web/src/main/js/app/components/nav/component/ComponentNav.tsx, server/sonar-web/src/main/js/app/components/nav/component/Header.tsx, server/sonar-web/src/main/js/app/components/nav/component/Menu.tsx, server/sonar-web/src/main/js/app/components/nav/component/branch-like/BranchLikeNavigation.tsx, server/sonar-web/src/main/js/app/components/nav/component/branch-like/Menu.tsx, server/sonar-web/src/main/js/app/components/nav/component/branch-like/MenuItemList.tsx, server/sonar-web/src/main/js/apps/projectBranches/components/App.tsx, server/sonar-web/src/main/js/apps/projectBranches/components/BranchLikeTabs.tsx, server/sonar-web/src/main/js/apps/projectBranches/components/LifetimeInformation.tsx, server/sonar-web/src/main/js/apps/projectBranches/components/LifetimeInformationRenderer.tsx, sonar-core/src/main/resources/org/sonar/l10n/core.properties
=> CD-2255: Fixed labels for Comparison Branches feature

server/sonar-webserver-auth/src/main/java/org/sonar/server/organization/OrganizationValidation.java, server/sonar-webserver-auth/src/main/java/org/sonar/server/organization/OrganizationValidationImpl.java, server/sonar-webserver-auth/src/test/java/org/sonar/server/organization/OrganizationValidationImplTest.java, server/sonar-webserver-webapi/src/test/java/org/sonar/server/organization/ws/CreateActionTest.java, server/sonar-webserver-webapi/src/test/java/org/sonar/server/organization/ws/UpdateActionTest.java
Validation is present from UI but not on server side. We can tamper the URL payload and server is accepting.
=> CD-2256 Added Org URL validation in back-end to prevent XSS security attack

build.gradle
CD-2518: Updated sonar-java-plugin to 7.6
=> CD-2518: Updated sonar-java-plugin to 7.6

server/sonar-web/src/main/js/helpers/standards.json
=> CD-2728: OWASP standards has been updated as per 2021 standards.

server/sonar-web/src/main/js/apps/create/project/CreateProjectPageSonarCloud.tsx, server/sonar-web/src/main/js/apps/create/project/ManualProjectCreate.tsx, server/sonar-web/src/main/js/apps/grc/create-Project/CreateProject.css, server/sonar-web/src/main/js/apps/grc/create-Project/CreateProject.tsx, server/sonar-web/src/main/js/apps/grc/create-Project/CreateProjectPage.tsx, server/sonar-web/src/main/js/apps/grc/nav/GrcGlobalNavMenu.tsx, server/sonar-web/src/main/js/apps/grc/routes.ts, server/sonar-web/src/main/js/helpers/urls.ts
=> Grc create project changes

server/sonar-web/src/main/js/helpers/standards.json
PR to update OWASP New Labels in Dreamforce branch
=> CD-2728: OWASP standards has been updated as per 2021 standards. (#74)

server/sonar-web/src/main/js/app/components/nav/global/GlobalNavUser.tsx, server/sonar-web/src/main/js/apps/create/project/ManualProjectCreate.tsx, server/sonar-web/src/main/js/apps/grc/create-Project/CreateProjectPage.tsx, server/sonar-web/src/main/js/apps/grc/nav/GrcGlobalNavMenu.tsx, server/sonar-web/src/main/js/apps/grc/nav/GrcProjects.tsx
=> user menu changes

server/sonar-web/src/main/js/apps/code/components/Components.tsx, server/sonar-web/src/main/js/apps/code/components/ComponentsHeader.tsx, server/sonar-web/src/main/js/apps/code/utils.ts, server/sonar-web/src/main/js/apps/grc/components/GrcPage.tsx, server/sonar-web/src/main/js/apps/grc/create-Project/CreateProjectPage.tsx, server/sonar-web/src/main/js/apps/grc/nav/GrcGlobalNavMenu.tsx, server/sonar-web/src/main/js/apps/grc/nav/GrcProjects.tsx, server/sonar-web/src/main/js/apps/overview/branches/MeasuresPanel.tsx, server/sonar-web/src/main/js/helpers/urls.ts, sonar-core/src/main/resources/org/sonar/l10n/core.properties
- Overview Page Changes
- Inventory Page Changes
- Dynamic Links
=> Navigation Links with Project Key

server/sonar-web/src/main/js/app/components/nav/global/GlobalNavMenu.tsx, server/sonar-web/src/main/js/types/types.d.ts
- Enhanced the condition to show the administration link, when user is part of sonar-administrators group
=> CD-2724: Added extra condition for showing administration link

server/sonar-web/src/main/js/app/components/nav/global/GlobalNav.tsx, server/sonar-web/src/main/js/apps/grc/create-Project/CreateProjectPage.tsx
=> minor observation fixes on navigations.

server/sonar-web/src/main/js/apps/code/components/App.tsx, server/sonar-web/src/main/js/apps/code/components/Breadcrumbs.tsx, server/sonar-web/src/main/js/apps/code/components/Component.tsx, server/sonar-web/src/main/js/apps/code/components/ComponentName.tsx, server/sonar-web/src/main/js/apps/code/components/Components.tsx, server/sonar-web/src/main/js/apps/code/components/SourceViewerWrapper.tsx, server/sonar-web/src/main/js/apps/code/utils.ts, server/sonar-web/src/main/js/apps/grc/components/GrcNewPage.tsx, server/sonar-web/src/main/js/apps/grc/components/GrcPage.tsx, server/sonar-web/src/main/js/apps/grc/grc-dashboard.css, server/sonar-web/src/main/js/apps/grc/routes.ts, server/sonar-web/src/main/js/apps/grc/styles.css, server/sonar-web/src/main/js/apps/overview/branches/BranchOverview.tsx, server/sonar-web/src/main/js/apps/overview/branches/BranchOverviewRenderer.tsx, server/sonar-web/src/main/js/apps/overview/branches/MeasuresPanel.tsx, server/sonar-web/src/main/js/apps/overview/branches/MeasuresPanelIssueMeasureRow.tsx, server/sonar-web/src/main/js/apps/overview/components/IssueLabel.tsx, server/sonar-web/src/main/js/apps/overview/styles.css, server/sonar-web/src/main/js/components/SourceViewer/SourceViewerBase.tsx, server/sonar-web/src/main/js/components/SourceViewer/SourceViewerHeader.tsx, server/sonar-web/src/main/js/helpers/constants.ts, server/sonar-web/src/main/js/helpers/urls.ts, sonar-core/src/main/resources/org/sonar/l10n/core.properties
- Reloading the GRC Dashboard Page, when the Project is changed
- Overview Page Linking
- Inventory Page Linking
- Hiding of Bugs, smells and one more part in Overview Page
- Update the links with proper urls for Inventory Page
=> Linking of Overview Page and Inventory Pages with Navigation.

server/sonar-web/src/main/js/apps/grc/components/IssuesByPriority.tsx, server/sonar-web/src/main/js/apps/grc/components/LastAnalysis.tsx, server/sonar-web/src/main/js/apps/grc/components/PolicyCount.tsx, server/sonar-web/src/main/js/apps/grc/components/RiskIndicator.tsx, server/sonar-web/src/main/js/apps/grc/dashboard/Dashboard.tsx, server/sonar-web/src/main/js/apps/grc/dashboard/utils.ts, server/sonar-web/src/main/js/apps/grc/grc-dashboard.css
- Integartion of the Last Analysis Widget
- Integration of the Total Policies, Policies Enforced
- Integration of the Violations by Priority.
=> Integration of the GRC Dashboard first row widgets with real data

server/sonar-web/src/main/js/apps/grc/components/GrcNewPage.tsx
=> fix for loading the create project page.

server/sonar-web/src/main/js/apps/grc/dashboard/Dashboard.tsx
- reading the apt value from response
=> Bug Fix: Policy Enforced Widget

server/sonar-web/src/main/js/app/components/nav/global/GlobalNav.css, server/sonar-web/src/main/js/apps/grc/analysis/GrcRerunAnalysis.tsx, server/sonar-web/src/main/js/apps/grc/nav/GrcGlobalNavMenu.tsx, server/sonar-web/src/main/js/apps/grc/routes.ts, server/sonar-web/src/main/js/apps/overview/branches/BranchOverviewRenderer.tsx, server/sonar-web/src/main/js/apps/overview/branches/QualityGatePanel.tsx, server/sonar-web/src/main/js/apps/overview/branches/QualityGatePanelSection.tsx, server/sonar-web/src/main/js/apps/overview/components/QualityGateCondition.tsx, server/sonar-web/src/main/js/apps/overview/components/QualityGateConditions.tsx, server/sonar-web/src/main/js/helpers/urls.ts
- Functionality added for ReRun Analysis Screen
- Fixed the issues on the Overview Page
=> Feature Rerun Analysis Screen

server/sonar-web/src/main/js/apps/grc/AddProject/AuthorizeForm.tsx
=> fixed minor Ui styling.

server/sonar-web/src/main/js/apps/coding-rules/components/App.tsx, server/sonar-web/src/main/js/apps/coding-rules/components/Facet.tsx, server/sonar-web/src/main/js/apps/coding-rules/components/FacetsList.tsx, server/sonar-web/src/main/js/apps/coding-rules/components/LanguageFacet.tsx, server/sonar-web/src/main/js/apps/coding-rules/components/RepositoryFacet.tsx, server/sonar-web/src/main/js/apps/coding-rules/query.ts, server/sonar-web/src/main/js/apps/grc/nav/GrcGlobalNavMenu.tsx, server/sonar-web/src/main/js/apps/grc/routes.ts, server/sonar-web/src/main/js/components/facet/FacetHeader.tsx, server/sonar-web/src/main/js/components/facet/ListStyleFacet.tsx, server/sonar-web/src/main/js/helpers/urls.ts
=> rules page changes for GRC.

server/sonar-web/src/main/js/apps/create/project/OrganizationInput.tsx, server/sonar-web/src/main/js/apps/grc/AddProject/AuthorizeForm.tsx, server/sonar-web/src/main/js/apps/grc/create-Project/CreateProject.tsx, server/sonar-web/src/main/js/apps/grc/create-Project/CreateProjectPage.tsx, server/sonar-web/src/main/js/apps/security-hotspots/components/EmptyHotspotsPage.tsx
=> Grc create project

server/sonar-web/src/main/js/apps/grc/routes.ts, server/sonar-web/src/main/js/apps/settings/components/AllCategoriesList.tsx, server/sonar-web/src/main/js/apps/settings/components/AppContainer.tsx, server/sonar-web/src/main/js/apps/settings/components/GrcDeAssocciate.tsx, server/sonar-web/src/main/js/apps/settings/styles.css, server/sonar-web/src/main/js/helpers/urls.ts
- Profile -> Policies (Breaking Links fixed)
- Settings Page
=> grc settings page

server/sonar-web/package.json, server/sonar-web/src/main/js/apps/grc/components/GrcViolations.tsx, server/sonar-web/src/main/js/apps/grc/components/IssuesByPriority.tsx, server/sonar-web/src/main/js/apps/grc/components/RiskIndicator.tsx, server/sonar-web/src/main/js/apps/grc/dashboard/Dashboard.tsx, server/sonar-web/src/main/js/apps/grc/grc-dashboard.css, server/sonar-web/yarn.lock
=> GRC Dashboard Enhancements

server/sonar-web/src/main/js/apps/grc/create-Project/CreateProject.tsx
=> changed the verbiage.

server/sonar-webserver-webapi/src/main/java/org/sonar/server/qualityprofile/ws/ShowAction.java
=> CD-2773: Updated Show action class to add organisation details.

server/sonar-web/src/main/js/apps/coding-rules/components/ActivationFormModal.tsx
=> CD-2867 Add Dropdown list option for SINGLE_SELECT_LIST parameter type

server/sonar-web/src/main/js/helpers/standards.json
=> Updated owasp standards.

server/sonar-docs/src/EmbedDocsSuggestions.json, server/sonar-web/src/main/js/app/components/GlobalFooterSonarCloud.tsx, server/sonar-web/src/main/js/app/components/embed-docs-modal/EmbedDocsPopup.tsx, server/sonar-web/src/main/js/apps/documentation/components/App.tsx, server/sonar-web/src/main/js/apps/organizationMembers/MembersPageHeader.tsx
Get Started with CodeScan Cloud: https://knowledgebase.autorabit.com/codescan/docs/codescan-getting-started 
Documentation: https://knowledgebase.autorabit.com/codescan 
Add Users:  https://knowledgebase.autorabit.com/codescan/docs/add-users-to-a-codescan-cloud-organisation
=> CD-2959 Update KB articles

sonar-core/src/main/resources/org/sonar/l10n/core.properties
Codescan Version update.  Release banner will be updated at a later point of time
=> update version to 22.8 in core.properties

server/sonar-web/src/main/js/app/components/nav/component/projectInformation/ProjectInformationRenderer.tsx, server/sonar-web/src/main/js/app/components/nav/component/projectInformation/meta/MetaQualityGate.tsx
=> CD-3181: Added organization key to the qualitygate search api.

server/sonar-docs/src/EmbedDocsSuggestions.json, server/sonar-server-common/src/main/java/org/sonar/server/webhook/WebHooksImpl.java, server/sonar-web/src/main/js/apps/webhooks/components/PageHeader.tsx
Change Log Level in WebhooksImpl.java in log method.
=> Cd 3226 webhook delivery logs

server/sonar-web/src/main/js/app/components/GlobalFooterSonarCloud.tsx
=> Added LGPL licence for codescan

server/sonar-web/src/main/js/app/components/nav/component/projectInformation/ProjectInformationRenderer.tsx, server/sonar-web/src/main/js/app/components/nav/component/projectInformation/meta/MetaQualityProfiles.tsx
=> Added organization parameter in issues api call at project level.

server/sonar-server-common/src/main/java/org/sonar/server/es/IndexType.java, server/sonar-server-common/src/main/java/org/sonar/server/es/SearchOptions.java, server/sonar-server-common/src/main/java/org/sonar/server/issue/SearchRequest.java, server/sonar-webserver-es/src/main/java/org/sonar/server/issue/index/IssueIndex.java, server/sonar-webserver-es/src/main/java/org/sonar/server/issue/index/IssueQuery.java, server/sonar-webserver-es/src/main/java/org/sonar/server/issue/index/IssueQueryFactory.java, server/sonar-webserver-webapi/src/main/java/org/sonar/server/issue/ws/SearchAction.java, server/sonar-webserver-webapi/src/main/java/org/sonar/server/issue/ws/SearchResponseFormat.java, sonar-ws/src/main/java/org/sonarqube/ws/client/issue/IssuesWsParameters.java, sonar-ws/src/main/protobuf/ws-issues.proto
=> Search after

build.gradle, sonar-ws/build.gradle, sonar-ws/src/main/java/org/sonarqube/ws/client/OkHttpClientBuilder.java
CD-2543	Resolve DNS cache issue
=> CD-2543	Resolve DNS cache issue

server/sonar-server-common/src/main/java/org/sonar/server/webhook/WebHooksImpl.java, server/sonar-webserver/src/main/java/org/sonar/server/platform/web/SecurityServletFilter.java, server/sonar-webserver/src/test/java/org/sonar/server/platform/web/SecurityServletFilterTest.java
CD-2019	Testing for Missing security headers
CD-3226	Unresolved Host - aligntech-int.codescan.io Investigation
=> CD-2019 -Testing for Missing security headers

server/sonar-main/src/main/java/org/sonar/application/AppLogging.java, server/sonar-main/src/test/java/org/sonar/application/AppLoggingTest.java
CD-2541 - Enable JSON logs encoder for consoler appender
=> CD-2541 - Enable JSON logs encoder for consoler appender

server/sonar-web/src/main/js/apps/home/components/home.tsx, server/sonar-web/src/main/js/store/users.ts
=> CD-3377 One-time splash page is displaying even if user Sign Up and log out from the application.

build.gradle, codescan-application/build.gradle, server/sonar-ce-task-projectanalysis/src/test/java/org/sonar/ce/task/projectanalysis/component/BranchPersisterImplTest.java, sonar-core/src/main/java/org/sonar/core/config/PurgeProperties.java, sonar-core/src/test/java/org/sonar/core/config/CorePropertyDefinitionsTest.java, sonar-core/src/test/java/org/sonar/core/config/PurgePropertiesTest.java
=> Sq9.9 migrate

build.gradle, server/sonar-webserver-api/src/main/java/org/sonar/server/util/KeyValueMapValidation.java, server/sonar-webserver-api/src/test/java/org/sonar/server/util/KeyValueMapValidationTest.java
Add artifactory details to sonarqube-9.9
=> CD-3450 - Add artifactory details to sonarqube-9.9

server/sonar-web/public/WEB-INF/web.xml, server/sonar-web/src/main/js/app/components/AdminContainer.tsx, server/sonar-web/src/main/js/app/components/nav/global/GlobalNavMenu.tsx, server/sonar-web/src/main/js/app/components/nav/settings/SettingsNav.tsx, server/sonar-web/src/main/js/app/utils/startReactApp.tsx, server/sonar-web/src/main/js/apps/settings/components/AllCategoriesList.tsx, server/sonar-web/src/main/js/apps/settings/components/AllCustomerCategories.tsx, server/sonar-web/src/main/js/apps/settings/constants.ts, server/sonar-web/src/main/js/components/embed-docs-modal/EmbedDocsPopup.tsx, server/sonar-webserver-webapi/src/main/java/org/sonar/server/ui/ws/GlobalAction.java, server/sonar-webserver/src/main/java/org/sonar/server/platform/web/CustomerAdminFilter.java
=> Sq9.9 migration

server/sonar-web/src/main/js/apps/settings/components/AllCategoriesList.tsx
fix admin settings page
Thank You!
=> fix admin settings page

server/sonar-db-dao/src/main/java/org/sonar/db/measure/ProjectMeasuresIndexerIterator.java, server/sonar-server-common/src/main/java/org/sonar/server/measure/index/ProjectMeasuresDoc.java, server/sonar-server-common/src/main/java/org/sonar/server/measure/index/ProjectMeasuresIndexDefinition.java, server/sonar-server-common/src/main/java/org/sonar/server/measure/index/ProjectMeasuresIndexer.java, server/sonar-web/src/main/js/api/components.ts, server/sonar-web/src/main/js/apps/organizations/components/OrganizationProjects.tsx, server/sonar-web/src/main/js/apps/organizations/routes.tsx, server/sonar-web/src/main/js/apps/projects/components/AllProjects.tsx, server/sonar-web/src/main/js/apps/projects/utils.ts, server/sonar-webserver-es/src/main/java/org/sonar/server/measure/index/ProjectMeasuresIndex.java, server/sonar-webserver-es/src/main/java/org/sonar/server/measure/index/ProjectMeasuresQuery.java, server/sonar-webserver-webapi/src/main/java/org/sonar/server/component/ws/SearchProjectsAction.java, sonar-ws/src/main/protobuf/ws-commons.proto, sonar-ws/src/main/protobuf/ws-components.proto
CD-3606-Projects created in Org1 are able to visible in Org2
=> CD-3606-Projects created in Org1 are able to visible in Org2

server/sonar-web/src/main/js/app/components/nav/global/GlobalNavMenu.tsx, server/sonar-web/src/main/js/app/utils/startReactApp.tsx, server/sonar-web/src/main/js/apps/settings/utils.ts, server/sonar-webserver-webapi/src/main/java/org/sonar/server/component/ws/SearchProjectsAction.java
Fixed displaying Administration menu item;
Fixed loading data on My Projects page;
Set CodeScan as default tab in Global Settings;
=> Fixed displaying Administration menu item and loading data on My Projects page

server/sonar-webserver-webapi/src/main/java/org/sonar/server/organization/ws/OrganizationsWsModule.java
CD-3729 - Unable to remove User from Organizations Members list
=> CD-3729 - Unable to remove User from Organizations Members list

server/sonar-db-dao/src/main/java/org/sonar/db/qualityprofile/DefaultQProfileDto.java, server/sonar-db-dao/src/main/resources/org/sonar/db/qualityprofile/DefaultQProfileMapper.xml
Fixed set default quality profile issue for organisation
=> Fixed set default quality profile issue for organization

server/sonar-server-common/src/main/java/org/sonar/server/es/IndexType.java, server/sonar-server-common/src/main/java/org/sonar/server/issue/SearchRequest.java, server/sonar-webserver-es/src/main/java/org/sonar/server/issue/index/IssueIndex.java, server/sonar-webserver-es/src/main/java/org/sonar/server/issue/index/IssueQuery.java, server/sonar-webserver-es/src/main/java/org/sonar/server/issue/index/IssueQueryFactory.java, server/sonar-webserver-webapi/src/main/java/org/sonar/server/issue/ws/SearchAction.java, server/sonar-webserver-webapi/src/main/java/org/sonar/server/issue/ws/SearchResponseFormat.java, sonar-ws/src/main/java/org/sonarqube/ws/client/issue/IssuesWsParameters.java, sonar-ws/src/main/protobuf/ws-issues.proto
=> Codescan 9.9 search after

server/sonar-web/src/main/js/apps/quality-profiles/details/ProfileRulesDeprecatedWarning.tsx
Fixed QP deprecated broken link
=> Fixed QP Deprecated Rules

server/sonar-ce-task-projectanalysis/src/main/java/org/sonar/ce/task/projectanalysis/step/SendIssueNotificationsStep.java, server/sonar-webserver-webapi/src/main/java/org/sonar/server/issue/ws/BulkChangeAction.java, server/sonar-webserver-webapi/src/main/java/org/sonar/server/issue/ws/IssueUpdater.java
Add changes part of commit 52a950f76b3727f37bd126b59a74c3ec9c3d298f
=> CD-3291 Add Notification for PR fix to SQ 9.9

server/sonar-web/scripts/start.js, server/sonar-web/src/main/js/apps/organizations/navigation/OrganizationNavigationMenu.tsx
=> CD-3512: Updated the label properties

server/sonar-web/src/main/js/apps/account/projects/ProjectCard.tsx, sonar-core/src/main/resources/org/sonar/l10n/core.properties
=> CD-3549 :: Updated labels

server/sonar-web/src/main/js/app/components/nav/global/GlobalNavMenu.tsx, sonar-core/src/main/resources/org/sonar/l10n/core.properties
=> CD-3770: Updated the label MY ISSUES

server/sonar-server-common/src/main/java/org/sonar/server/issue/SearchRequest.java, server/sonar-webserver-webapi/src/main/java/org/sonar/server/issue/ws/SearchAction.java, sonar-ws/src/main/java/org/sonarqube/ws/client/issue/IssuesWsParameters.java
…we have no projects analysed in the Org
Thank You!
=> CD-3738 All the issues are getting listed in the New Org even though we have no projects analysed in the Org

server/sonar-web/src/main/js/apps/overview/branches/MeasuresPanel.tsx
=> CD-3771: Fix for the issue

server/sonar-web/src/main/js/apps/organizations/components/OrganizationDelete.tsx
=> CD-3725: refreshing the page, when deleteing organization

server/sonar-web/src/main/js/app/components/nav/component/Menu.tsx, server/sonar-web/src/main/js/apps/organizations/navigation/OrganizationNavigationExtensions.tsx
=> Hiding the Project Job Link and Request Error Links

server/sonar-db-dao/src/main/java/org/sonar/db/rule/RuleForIndexingDto.java
CD-3777 : Custom rule fix
Thank You!
=> CD-3777 : Custom rule fix

server/sonar-web/src/main/js/api/codescan.ts, server/sonar-web/src/main/js/apps/organizations/navigation/OrganizationNavigation.tsx, server/sonar-web/src/main/js/components/ui/NavBarTabs.css
=> CD-3762: Added Fix

server/sonar-web/src/main/js/apps/organizations/navigation/OrganizationNavigation.tsx, server/sonar-web/src/main/js/components/ui/NavBarTabs.css
=> CD-3821: Made the css specific

server/sonar-web/src/main/js/apps/organizations/components/OrganizationLink.tsx, server/sonar-web/src/main/js/apps/organizations/navigation/OrganizationNavigation.tsx
=> CD-3833: Fixed Console Errors

server/sonar-web/src/main/js/apps/quality-profiles/components/ProfileActions.tsx
=> Removed duplicate spaces for quality profile search

sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/ActivateRulesRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/AddGroupRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/AddProjectRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/AddUserRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/BackupRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/ChangeParentRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/ChangelogRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/CreateRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/DeactivateRulesRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/DeleteRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/ExportRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/InheritanceRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/QualityprofilesService.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/RemoveGroupRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/RemoveProjectRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/RemoveUserRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/RestoreRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/SearchGroupsRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/SearchRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/SearchUsersRequest.java, sonar-ws/src/main/java/org/sonarqube/ws/client/qualityprofiles/SetDefaultRequest.java
=> Added Organization parameter to backup service

server/sonar-webserver-webapi/src/main/java/org/sonar/server/qualityprofile/ws/BackupAction.java
=> Added Org parameter in BackupAction class.

server/sonar-web/src/main/js/apps/security-hotspots/components/HotspotOpenInIdeButton.tsx
=> Remove open in IDE button in hotspot page

server/sonar-web/src/main/js/apps/issues/components/IssuesApp.tsx
=> CD-3843: Added Fix

server/sonar-webserver/src/main/java/org/sonar/server/platform/web/CspFilter.java
relax CSP filter to allow pendo, google tag manager and full story to function correctly
https://help.fullstory.com/hc/en-us/articles/360020622854-Can-I-use-Content-Security-Policy-CSP-with-FullStory-
https://support.pendo.io/hc/en-us/articles/360032209131-Content-Security-Policy-CSP-
https://developers.google.com/tag-platform/tag-manager/csp
=> CD-3848 CSP relaxation for pendo,fs,gtm

server/sonar-web/src/main/js/apps/issues/components/IssuesApp.tsx, server/sonar-web/src/main/js/types/types.ts
=> Added orgnization parameter for issues in global nav bar.

server/sonar-web/src/main/js/apps/create/components/OrganizationAvatarInput.tsx, server/sonar-web/src/main/js/apps/create/components/OrganizationAvatarUrlInput.tsx, server/sonar-web/src/main/js/apps/create/components/OrganizationNameInput.tsx, server/sonar-web/src/main/js/apps/create/organization/OrganizationDetailsForm.tsx, server/sonar-web/src/main/js/apps/organizations/components/OrganizationEdit.tsx, sonar-core/src/main/resources/org/sonar/l10n/core.properties
=> CD-3914: Added misc fixes

server/sonar-web/src/main/js/apps/organizations/components/OrganizationEdit.tsx
=> CD-3914: added notification

server/sonar-web/src/main/js/apps/quality-profiles/home/PageHeader.tsx, server/sonar-web/src/main/js/apps/quality-profiles/home/RestoreProfileForm.tsx
CD-3945 : Restore Quality Profiles
Thank You!
=> CD-3945 : Restore Quality Profiles

server/sonar-web/src/main/js/apps/coding-rules/components/ActivationFormModal.tsx
=> CD-3851: Added Fix

server/sonar-web/src/main/js/app/components/FormattingHelp.tsx, server/sonar-web/src/main/js/components/issue/components/IssueMessageTags.tsx, sonar-core/src/main/resources/org/sonar/l10n/core.properties
=> Added rebranding to codescan.

server/sonar-webserver-auth/src/main/java/org/sonar/server/user/TokenUserSession.java
Add permission check for Token User Session flow.
=> Add hasPermissionImpl for org perm check - Token User Session

server/sonar-web/src/main/js/apps/create/components/OrganizationAvatarInput.tsx, server/sonar-web/src/main/js/apps/create/components/OrganizationAvatarUrlInput.tsx, server/sonar-web/src/main/js/apps/users/components/TokensForm.tsx, server/sonar-web/src/main/js/helpers/constants.ts, server/sonar-web/src/main/js/types/appstate.ts
Add feature flag for amazon specific changes in sonarqube UI
=> CD-3974 CD-3915 CD-3914 feature flag for amazon

server/sonar-web/src/main/js/apps/create/components/OrganizationAvatarInput.tsx, server/sonar-web/src/main/js/apps/create/components/OrganizationAvatarUrlInput.tsx, server/sonar-web/src/main/js/apps/users/components/TokensForm.tsx, server/sonar-web/src/main/js/helpers/constants.ts, server/sonar-web/src/main/js/types/appstate.ts
This reverts commit 72e8e552cdf6e46a34208835342e8e339f69457a.
=> Revert "CD-3974 CD-3915 CD-3914 feature flag for amazon (#285)"

server/sonar-web/src/main/js/apps/coding-rules/components/RuleDetailsMeta.tsx
=> CD-3976: Updated the organization properly.

server/sonar-webserver-core/src/main/java/org/sonar/server/platform/web/RootFilter.java, server/sonar-webserver-webapi/src/main/java/org/sonar/server/project/ws/CreateAction.java
=> Added log messages.

server/sonar-web/src/main/js/apps/organizations/navigation/OrganizationNavigationMeta.tsx, server/sonar-web/src/main/js/apps/policy-results/components/PolicyResults.tsx, server/sonar-web/src/main/js/types/users.ts
=> CD-3979 : Fix for Policy Results while clicking on Home Icon

server/sonar-web/src/main/js/apps/marketplace/App.tsx, sonar-core/src/main/resources/org/sonar/l10n/core.properties
Removed Editions box, fixed formatting and added CodeScan Text
=> edit sq text, fix formatting, remove EditionBox

server/sonar-web/src/main/js/apps/create/components/OrganizationUrlInput.tsx
=> Added domain validation for the url field

server/sonar-db-dao/src/main/java/org/sonar/db/rule/RuleDao.java, server/sonar-db-dao/src/main/java/org/sonar/db/rule/RuleMapper.java, server/sonar-db-dao/src/main/resources/org/sonar/db/rule/RuleMapper.xml
fix-ruletag-deletion
Thank You!
=> fix-ruletag-deletion

server/sonar-web/src/main/js/apps/policy-results/components/PolicyResults.tsx
=> CD-4024: Fixing the continous spinner issue

server/sonar-web/package.json, server/sonar-web/yarn.lock
=> CD-4023: Updating the react-select version

server/sonar-web/src/main/js/apps/create/components/OrganizationAvatarInput.tsx, server/sonar-web/src/main/js/apps/create/components/OrganizationAvatarUrlInput.tsx, server/sonar-web/src/main/js/apps/create/components/OrganizationUrlInput.tsx, server/sonar-web/src/main/js/helpers/constants.ts, server/sonar-web/src/main/js/helpers/urls.ts, server/sonar-web/src/main/js/types/appstate.ts
=> CD-3993: Validating whether whitelistvalue is Amazon or not

server/sonar-web/src/main/js/app/components/nav/component/branch-like/CurrentBranchLike.tsx
=> Cd 3959: Removed the extra 2 links

server/sonar-web/src/main/js/apps/users/components/TokensForm.tsx, server/sonar-web/src/main/js/helpers/urls.ts
=> CD-4060: Added logic to show usertoken only for amazon

server/sonar-web/src/main/js/components/controls/buttons.css
=> CD-4044 update disabled button styling

server/sonar-process/src/main/java/org/sonar/process/logging/LogbackHelper.java
=> added web log pattern

server/sonar-db-dao/src/main/java/org/sonar/db/organization/OrganizationQuery.java, server/sonar-db-dao/src/main/resources/org/sonar/db/organization/OrganizationMapper.xml, server/sonar-webserver-webapi/src/main/java/org/sonar/server/organization/ws/OrganizationsWsModule.java, server/sonar-webserver-webapi/src/main/java/org/sonar/server/organization/ws/SearchAction.java
=> Cd 4079 - Added member functionality to get orgaanization

server/sonar-web/src/main/js/components/ui/NavBar.css
=> CD-4087: Alignment of Organization and project names are not proper.

server/sonar-main/src/main/java/org/sonar/application/command/CommandFactoryImpl.java
=> Add sonar-codescancloud-plugin to classpath

sonar-scanner-engine/src/main/java/org/sonar/scanner/scan/branch/ProjectBranches.java
=> Don't use main as a default branch name in SaaS instance

server/sonar-web/src/main/js/apps/projectsManagement/CreateProjectForm.tsx, server/sonar-web/src/main/js/apps/projectsManagement/Search.tsx
=> CD-4097: User is allowed to create public projects instead he should allow only private projects creation

server/sonar-web/src/main/js/app/components/nav/component/Menu.tsx, server/sonar-web/src/main/js/app/utils/startReactApp.tsx
=> CD-4135: Import/Export option should be removed under Project settings of a project.

server/sonar-db-migration/src/main/java/org/sonar/server/platform/db/migration/version/v99/AddOnboardedColumnToUsersTable.java, server/sonar-db-migration/src/main/java/org/sonar/server/platform/db/migration/version/v99/DbVersion99.java, server/sonar-db-migration/src/main/java/org/sonar/server/platform/db/migration/version/v99/UpsertOnboardedValue.java
Fix for ERROR
column u.onboarded does not exist
The error may exist in org.sonar.db.user.UserMapper
The error may involve org.sonar.db.user.UserMapper.selectUserByLogin
=> add onboarded column in users

codescan-application/bundled_plugins.gradle
=> build php plugin

server/sonar-webserver-webapi/src/main/java/org/sonar/server/project/ws/CreateAction.java, server/sonar-webserver-webapi/src/main/java/org/sonar/server/ui/ws/OrganizationAction.java
=> CD-4136 Resticted to create public projects in codescan

server/sonar-webserver-webapi/src/main/java/org/sonar/server/component/ComponentCleanerService.java, server/sonar-webserver-webapi/src/main/java/org/sonar/server/issue/ws/SetSeverityAction.java, server/sonar-webserver-webapi/src/main/java/org/sonar/server/project/ws/CreateAction.java, server/sonar-webserver-webapi/src/main/java/org/sonar/server/project/ws/DeleteAction.java
=> added logs for aws

server/sonar-web/src/main/js/components/embed-docs-modal/EmbedDocsPopup.tsx
[CD-4271] | Fix Get help issue by encoding full name which can consist of multiple words
=> [CD-4271] |  Fix Get help issue by encoding full name which can consist of multiple words

server/sonar-main/src/main/java/org/sonar/application/command/CommandFactoryImpl.java
=> Added plugin path to SQ after SQ-9.9 upgrade.

server/sonar-web/src/main/js/components/embed-docs-modal/EmbedDocsPopup.tsx
1. Encode full name just before creating zoho url
=> [CD-4271] | Bug Fix for get help.

server/sonar-web/src/main/js/apps/security-hotspots/components/HotspotHeader.tsx, server/sonar-web/src/main/js/apps/security-hotspots/components/assignee/Assignee.tsx, server/sonar-web/src/main/js/apps/security-hotspots/components/assignee/AssigneeSelection.tsx
[CD-4405] | Fix security hotspot assignee selection issue cause by not having organization changes.
=> [CD-4405] | Fix security hotspot assignee selection issue cause by not having organization changes.

server/sonar-web/src/main/js/apps/quality-profiles/compare/ComparisonResultActivation.tsx, server/sonar-web/src/main/js/apps/quality-profiles/compare/ComparisonResults.tsx
[CD-4371] Fixed rule activation issue during quality profile comparison
=> [CD-4371] Fixed rule activation issue during quality profile comparison

server/sonar-db-dao/src/main/java/org/sonar/db/qualitygate/QualityGateConditionDao.java, server/sonar-db-dao/src/main/java/org/sonar/db/qualitygate/QualityGateConditionMapper.java, server/sonar-db-dao/src/main/resources/org/sonar/db/qualitygate/QualityGateConditionMapper.xml, server/sonar-webserver-webapi/src/main/java/org/sonar/server/qualitygate/ws/DestroyAction.java
cleanup qGate conditions table on delete of qGate
=> cleanup qGate conditions on delete of qGate

server/sonar-db-dao/src/main/java/org/sonar/db/qualitygate/QualityGateConditionDao.java, server/sonar-db-dao/src/main/java/org/sonar/db/qualitygate/QualityGateConditionMapper.java, server/sonar-db-dao/src/main/java/org/sonar/db/qualitygate/QualityGateDao.java, server/sonar-db-dao/src/main/java/org/sonar/db/qualitygate/QualityGateMapper.java, server/sonar-db-dao/src/main/resources/org/sonar/db/qualitygate/QualityGateConditionMapper.xml, server/sonar-db-dao/src/main/resources/org/sonar/db/qualitygate/QualityGateMapper.xml, server/sonar-webserver-webapi/src/main/java/org/sonar/server/qualitygate/ws/DestroyAction.java
[CD-4483] | Removing qaulity gate record from org_quality_gates table when quality gate is deleted
=> [CD-4483] | Removing qaulity gate record from org_quality_gates table when quality gate is deleted

server/sonar-server-common/src/main/java/org/sonar/server/es/EsClientProvider.java
CD-4427-Configure-ES-Clustering
=> CD-4427-Configure-ES-Clustering

server/sonar-webserver-auth/src/main/java/org/sonar/server/authentication/UserSessionInitializer.java
Restrict HTTP 200 response for Un-Authenticated calls
=> CD-4557 Restrict HTTP 200 response for Un-Authenticated calls

server/sonar-web/src/main/js/components/embed-docs-modal/EmbedDocsPopup.tsx
Replace encodeURI with encodeURIComponent since it encode + (plus) symbol as well
=> [CD-4522] Replace encodeURI with encodeURIComponent since it encode + (plus) symbol as well

server/sonar-web/src/main/js/app/components/SonarLintConnection.tsx, server/sonar-web/src/main/js/apps/users/components/TokensFormItem.tsx, server/sonar-web/src/main/js/components/intl/DateTimeFormatter.tsx, server/sonar-web/src/main/js/helpers/tokens.ts, server/sonar-webserver-auth/src/main/java/org/sonar/server/authentication/UserSessionInitializer.java, server/sonar-webserver-webapi/src/main/java/org/sonar/server/usertoken/ws/GenerateAction.java, server/sonar-webserver-webapi/src/main/java/org/sonar/server/usertoken/ws/GenerateActionValidation.java
[CD-4530] | 1. Created short-lived 8 hours tokens for Amazon when initiated from IDE. 2. Display token expiry time along with date on security page.
=> [CD-4530] | 1. Created short-lived 8 hours tokens for Amazon when initiated from IDE. 2. Display token expiry time along with date on security page.

server/sonar-web/src/main/js/app/components/SonarLintConnection.tsx
[CD-4530] | 1. Removing logo of sonarlint at one more place
=> [CD-4530] | 1. Removing logo of sonarlint at one more place

build.gradle, settings.gradle
Update the Plugin Repository to plugins.gradle.org
=> Plugin Repo Update

server/sonar-db-dao/src/main/resources/org/sonar/db/user/UserTokenMapper.xml
[CD-4676] | 1. Sort User tokens by creation date DESC
=> [CD-4676] | 1. Sort User tokens by creation date DESC

server/sonar-web/src/main/js/app/components/nav/global/GlobalNavUser.tsx
CD 4677, Add instance parameter to segregate environments in Pendo
=> Cd 4677 pendo update

server/sonar-web/src/main/js/apps/sessions/components/OAuthProviders.tsx, server/sonar-web/src/main/js/apps/sessions/components/SamlLogin.tsx
[CD-4697] | Passing return_to param in SamlLogin
=> [CD-4697] | Passing return_to param in SamlLogin. Kindly don’t merge it right now. Needs some refactoring. Raised PR to get quick feedback

server/sonar-web/src/main/js/app/components/SonarLintConnection.tsx, server/sonar-web/src/main/js/helpers/sonarlint.ts, server/sonar-webserver-webapi/src/main/java/org/sonar/server/component/ws/SearchAction.java, server/sonar-webserver-webapi/src/main/java/org/sonar/server/usertoken/ws/GenerateAction.java, sonar-ws/src/main/protobuf/ws-user_tokens.proto
[CD-4741] | Creation of project level token for VSCode plugin
=> [CD-4741] | Creation of project level token for VSCode plugin

server/sonar-webserver-webapi/src/main/java/org/sonar/server/hotspot/ws/SearchAction.java, server/sonar-webserver-webapi/src/main/java/org/sonar/server/issue/ws/SearchAction.java
[CD-4846] Handling of project analysis token in issue search and hotspot search api.
=> [CD-4846] Handling of project analysis token in issue search and hotspot search api.

server/sonar-web/src/main/js/helpers/urls.ts
https://github.com/codescan-io/sonarqube/assets/74111708/64b39362-f37d-4a43-8314-8c9400fabedf
=> CD 5185 Update getOrgIssues URL to include query parameters

server/sonar-web/src/main/js/api/codescan.ts, server/sonar-web/src/main/js/components/embed-docs-modal/EmbedDocsPopup.tsx
=> [CD-5698] Modify ZOHO API

server/sonar-web/config/indexHtmlTemplate.js
[CD-5916] Remove google analytics and pendo scripts
=> [CD-5916] Remove google analytics and pendo scripts

server/sonar-web/src/main/js/components/ui/ContextNavBar.css, server/sonar-web/src/main/js/components/ui/NavBarTabs.css
Currently our Bitbucket projects have been updated with a safer webhook mechanism and we have added a message for our users to reattach their projects,  It is not showing correctly at the moment.
=> CD-5873 bitbucket reattach message formatted

build.gradle
This is to check if the custom changes are causing - Error creating bean with name 'ClassRealm{javascript}-org.sonar.plugins.javascript.bridge.Environment'
=> revert sonarjs vulnerability changes

server/sonar-process/src/main/java/org/sonar/process/logging/DataMaskingPatternClassicLayout.java, server/sonar-process/src/main/java/org/sonar/process/logging/LogMaskingUtil.java, server/sonar-process/src/main/java/org/sonar/process/logging/LogbackJsonLayout.java, server/sonar-webserver-auth/src/main/java/org/sonar/server/authentication/UserSessionInitializer.java, server/sonar-webserver/src/main/java/org/sonar/server/app/DataMaskingPatternAccessLayout.java, server/sonar-webserver/src/main/java/org/sonar/server/app/PatternAccessLayoutEncoder.java, server/sonar-webserver/src/main/java/org/sonar/server/app/TomcatAccessLog.java, server/sonar-webserver/src/main/java/org/sonar/server/platform/web/UserSessionFilter.java
[CF-7-NEW] Mask email in application and access logs.
=> [CF-7-NEW] Mask email in application and access logs.

server/sonar-db-dao/src/main/resources/org/sonar/db/property/PropertiesMapper.xml, server/sonar-webserver-webapi/src/main/java/org/sonar/server/organization/ws/MemberUpdater.java
[CD-6236] | Fix remove member from organization
=> [CD-6236] | Fix remove member from organization

codescan-application/build.gradle
=> [codescan-10-fix] | Fix codescan-zip min size issue

server/sonar-web/src/main/js/app/components/nav/component/Menu.tsx
More tab is always active under project analysis page. This needs to be fixed.
=> CD-6245 Horizontal blue line is appearing under more tab on project analysis page
